version: "3.9"
services:

 redis:
    image: "redis:alpine"
    command: redis-server --requirepass sOmE_sEcUrE_pAsS
    ports:
     - "6379:6379"
    volumes:
     - $PWD/config/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
     - REDIS_REPLICATION_MODE=master
    networks:
      node_net:
        ipv4_address: 127.0.0.1

# networking for the Redis container
networks:
  node_net:
    ipam:
      driver: default
      config:
        - subnet: 127.0.0.0/16