openapi: "3.0.0"
info:
  description: "Vacancy API."
  version: "1.0.0"
  title: "Vacancy, Candidates, Company store"
  contact:
    name: "admin"
    email: "admin@example.io"
host: "example.io"
basePath: "/api/v1"
tags:
- name: "vacancy"
  description: "Everything about IT-vacancies"
  externalDocs:
    description: "Find out more about vacancies"
    url: "http://example.io"
schemes:
- "http"
paths:
  /vacancy:
    get:
      tags:
      - "vacancy"
      summary: ""
      description: "Returns lists of vacancies"
      operationId: "getVacancy"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Vacancy"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Vacancy not found"
    post:
      tags:
      - "vacancy"
      summary: "Add a new vacancy"
      description: ""
      operationId: "addVacancy"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Vacancy object that needs to be added"
        required: true
        schema:
          $ref: "#/definitions/Vacancy"
      responses:
        "405":
          description: "Invalid input"
  /vacancy/{vacancyId}:
    get:
      tags:
      - "vacancy"
      summary: "Find vacancy by ID"
      description: "Returns a single vacancy"
      operationId: "getVacancyById"
      produces:
      - "application/json"
      parameters:
      - name: "vacancyId"
        in: "path"
        description: "ID of vacancy to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Vacancy"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Vacancy not found"
    put:
      tags:
      - "vacancy"
      summary: "Update an existing vacancy"
      description: ""
      operationId: "updateVacancy"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Vacancy object that needs to be added to the store"
        required: true
        schema:
          $ref: "#/definitions/Vacancy"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Vacancy not found"
        "405":
          description: "Validation exception"
    delete:
      tags:
      - "vacancy"
      summary: "Deletes a vacancy"
      description: ""
      operationId: "deleteVacancy"
      produces:
      - "application/json"
      parameters:
      - name: "vacancyId"
        in: "path"
        description: "Vacancy id to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Vacancy not found"
definitions:
  Vacancy:
    type: "object"
    required:
    - "company_name"
    - "vacancy_name"
    - "vacancy_description"
    - "key_skill"
    properties:
      id:
        type: "integer"
        format: "int64"
      company_name:
        $ref: "#/definitions/Employer"
      vacancy_name:
        type: "string"
      vacancy_description:
        type: "string"
      key_skill:
        $ref: "#/definitions/Technology"
      salary_min:
        type: "number"
        format: "float"
      salary_max:
        type: "number"
        format: "float"
      currency:
        type: "string"
        enum:
        - "RUB"
        - "EUR"
        - "USD"
      publish_date:
        type: "string"
        format: "date"
      is_active:
        type: "boolean"
        default: true
        description: "vacancy status"
  Employer:
    type: "object"
    required:
    - "company_name"
    - "site"
    - "address"
    properties:
      id:
        type: "integer"
        format: "int64"
      company_name:
        type: "string"
      description:
        type: "string"
      site:
        type: "string"
      address:
        type: "string"
      update_date:
        type: "string"
        format: "date-time"
  Technology:
    type: "object"
    required:
    - "name"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"