# Generated by Django 3.1.7 on 2021-05-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_create_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('site', models.CharField(max_length=100)),
                ('vacancy_name', models.CharField(max_length=50)),
                ('vacancy_description', models.TextField(max_length=200)),
                ('salary_min', models.IntegerField(blank=True, null=True)),
                ('salary_max', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(
                    choices=[('r', 'RUB'), ('e', 'EUR'), ('u', 'USD')], default='r', max_length=1)
                 ),
                ('publish_date', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'vacancy_employer_view',
                'managed': False,
            },
        ),
    ]
